### ISSUE TITLE
Add google places exception handling

### ISSUE THREAD

**Issue by ArturBorowy** [ArturBorowy/Pins#5]

**Comment by ArturBorowy** [comment]
2024-01-03 20:38:33.341  4596-4596  AndroidRuntime        E  FATAL EXCEPTION: main
                                                             Process: com.arturborowy.pins, PID: 4596
                                                             java.io.IOException: flfh: DEADLINE_EXCEEDED: Deadline CallOptions will be exceeded in 4.980949846s. 
                                                             	at android.location.Geocoder$SynchronousGeocoder.getResults(Geocoder.java:388)
                                                             	at android.location.Geocoder.getFromLocationName(Geocoder.java:277)
                                                             	at android.location.Geocoder.getFromLocationName(Geocoder.java:202)
                                                             	at com.arturborowy.pins.model.places.GooglePlacesClientRepository.getPlaceAddress(GooglePlacesClientRepository.kt:92)
                                                             	at com.arturborowy.pins.model.places.GooglePlacesClientRepository.access$getPlaceAddress(GooglePlacesClientRepository.kt:17)
                                                             	at com.arturborowy.pins.model.places.GooglePlacesClientRepository$getPlaceDetails$2$1.onComplete(GooglePlacesClientRepository.kt:66)
                                                             	at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
                                                             	at android.os.Handler.handleCallback(Handler.java:942)
                                                             	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                             	at android.os.Looper.loopOnce(Looper.java:226)
                                                             	at android.os.Looper.loop(Looper.java:313)
                                                             	at android.app.ActivityThread.main(ActivityThread.java:8762)
                                                             	at java.lang.reflect.Method.invoke(Native Method)
                                                             	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
                                                             	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
                                                             	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a42b932, Dispatchers.Main.immediate]
